version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "dokku-postgres-venduredb:5432", "--", "yarn", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE_HOST: dokku-postgres-venduredb
      DATABASE_PORT: 5432
    depends_on:
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE_HOST: dokku-postgres-venduredb
      DATABASE_PORT: 5432
