version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "postgres:5432", "--", "yarn", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE_HOST: '172.18.0.1'
      DATABASE_PORT: 5432
    depends_on:
      - database
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "postgres:5432", "--", "yarn", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE_HOST: '172.18.0.1'
      DATABASE_PORT: 5432
    depends_on:
      - database
  storefront:
    build:
      context: ../../front/storefront-remix-starter
      dockerfile: ../../backend/vendure-docker-compose/Dockerfile-storefront
    ports:
      - 8788:8788
    environment:
      SERVER_API_HOST: http://172.18.0.1:3000
      SERVER_API_PORT: 3000
      SERVER_API_PATH: shop-api  
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
